Implemented a new feature of generating charts
OS-Tech-Labs/Preprocessor pull request #3
Opened 2024-06-26 08:56 UTC by OmalyaV

A new feature is being created.
Graph generating according to user preference.

2024-07-01 20:07 UTC, OmalyaV commented
@samithkavishke 
I have added a new feature to generate graphs with user preference.
A SQLite database is integrated to store the generated images temporarily.
However, when the extensio is deactivated, the images should be deleted too. That functionality is not working properly.

2024-07-02 03:21 UTC, samithkavishke requested changes
Change those, I will look into the database problem

2024-07-02 03:21 UTC, samithkavishke commented on extension.js
>    const { spawn } = require("child_process")
Better to put all the imports at the top

2024-07-02 03:21 UTC, samithkavishke commented on media/script.js
> +console.log("Script loaded");
Remove redundant logging for debugs.

2024-07-02 03:21 UTC, samithkavishke commented on media/script.js
> +                            summaryHtml += '<td>' + summaryData[key]['75%'] + '</td>';
better to put in an extracted helper function

2024-07-16 13:06 UTC, merged